version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d postgres -U postgres -h localhost -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init-script.sh:/usr/local/bin/postgres-init-script.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POS_ADMIN_PASSWORD=pos_admin
      - APP_OWNER_PASSWORD=app_owner
      - APP_USER_PASSWORD=app_user
#    cannot run postgres-init-script.sh as command because postgres is not initialized yet
#    command: ["sh", "-c", "chmod +x /usr/local/bin/postgres-init-script.sh && /usr/local/bin/postgres-init-script.sh"]
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3.arm64
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.4.3.arm64
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_INTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
